//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: HelloWorldData.cpp
//  Source: ../../idl/HelloWorldData.idl
//  Generated: Sat Aug  5 01:02:22 2017
//  OpenSplice 6.8.0
//  
//******************************************************************

#include "HelloWorldData.h"




