//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: HelloWorldData.cpp
//  Source: ../../idl/HelloWorldData.idl
//  Generated: Sun May 21 08:09:53 2017
//  OpenSplice 6.8.0
//  
//******************************************************************

#include "HelloWorldData.h"




